#!/bin/bash

function help () {
 echo "usage: rod [ruby|scala|go]"
}

lang=$1
case $lang in
  ruby)  repl=pry;;
  scala) repl=amm;;
  go)    repl=gore;;
  *)     help && exit;;
esac

if [ -f /etc/repls-on-docker ]; then
  $repl
else
  docker run -it kyagi/rod $repl
fi
